const destinations = [
    {
        image:"",
        title:"",
        description:""
    },
    {
        image:"",
        title:"",
        description:""
    },
    {
        image:"",
        title:"",
        description:""
    },
    {
        image:"",
        title:"",
        description:""
    },
    {
        image:"",
        title:"",
        description:""
    },
    {
        image:"",
        title:"",
        description:""
    },
]